import type { Ride } from "@/features/manage-booking/types/ride";

export const MOCK_RIDES: Ride[] = [
  {
    id: "FLY-2026-8847",
    tab: "upcoming",
    status: "confirmed",
    direction: "From Ben Gurion Airport",
    from: "Ben Gurion Airport, Terminal 3",
    to: "Tel Aviv - Dizengoff St 55",
    pickup: "Ben Gurion Airport, Terminal 3",
    destination: "Tel Aviv - Dizengoff St 55, Tel Aviv-Yafo",
    dateTime: "Thursday, 14:30",
    date: "Thursday, 15 October 2026",
    time: "14:30",
    flight: "LY315",
    passengers: "2 adults",
    luggage: "2 bags",
    vehicle: "Standard Sedan",
    payment: "Credit Card",
    paymentDetail: "Credit Card · Paid Online",
    fareAmount: 280,
    driverAssigned: true,
    driver: {
      name: "Moshe Levi",
      rating: 4.92,
      trips: 487,
      verified: true,
      vehicle: "Toyota Corolla",
      color: "Silver",
      license: "123-45-678",
    },
  },
  {
    id: "FLY-2026-8848",
    tab: "upcoming",
    status: "confirmed",
    direction: "From Ben Gurion Airport",
    from: "Ben Gurion Airport, Terminal 3",
    to: "Tel Aviv - Dizengoff St 55",
    pickup: "Ben Gurion Airport, Terminal 3",
    destination: "Tel Aviv - Dizengoff St 55, Tel Aviv-Yafo",
    dateTime: "Thursday, 14:30",
    date: "Thursday, 15 October 2026",
    time: "14:30",
    flight: "LY315",
    passengers: "2 adults",
    luggage: "2 bags",
    vehicle: "Standard Sedan",
    payment: "Credit Card",
    paymentDetail: "Credit Card · Paid Online",
    fareAmount: 280,
    driverAssigned: false,
  },
  {
    id: "FLY-2026-7721",
    tab: "history",
    status: "completed",
    direction: "From Ben Gurion Airport",
    from: "Ben Gurion Airport, Terminal 3",
    to: "Tel Aviv - Dizengoff St 55",
    pickup: "Ben Gurion Airport, Terminal 3",
    destination: "Tel Aviv - Dizengoff St 55, Tel Aviv-Yafo",
    dateTime: "Thursday, 14:30",
    date: "Thursday, 10 September 2026",
    time: "14:30",
    passengers: "1 adults",
    luggage: "Trolley / Carry-on: 1",
    vehicle: "Standard Sedan",
    payment: "Bit",
    paymentDetail: "Bit · Paid to driver",
    fareAmount: 280,
  },
  {
    id: "FLY-2026-6612",
    tab: "history",
    status: "cancelled",
    direction: "From Ben Gurion Airport",
    from: "Ben Gurion Airport, Terminal 3",
    to: "Tel Aviv - Dizengoff St 55",
    pickup: "Ben Gurion Airport, Terminal 3",
    destination: "Tel Aviv - Dizengoff St 55, Tel Aviv-Yafo",
    dateTime: "Thursday, 14:30",
    date: "Thursday, 3 September 2026",
    time: "14:30",
    passengers: "1 adults",
    luggage: "Trolley / Carry-on: 1",
    vehicle: "Standard Sedan",
    payment: "Credit Card",
    fareAmount: 280,
  },
];

export function getRideById(id: string): Ride | undefined {
  return MOCK_RIDES.find((ride) => ride.id === id);
}

export function getRidesByTab(tab: Ride["tab"]): Ride[] {
  return MOCK_RIDES.filter((ride) => ride.tab === tab);
}
